services:

  # Import 'command' for local development
  import:
    build:
      args:
        PYTHON_IMAGE: ${PYTHON_IMAGE:-python:3.11.3-slim}
        UID: "${UID:-1000}"
      context: ./
      dockerfile: Dockerfile
    command: pipenv run import_all
    env_file: .env.import
    environment:
      API_BASE_URL:  http://localhost:8000
    network_mode: host
    volumes:
      - type: bind
        source: ./e2e_datafiles
        target: /app/e2e_datafiles
        read_only: true
      - type: bind
        source: ./datafiles
        target: /app/datafiles
        read_only: true
